config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'friendships/index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root 'posts#index'
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :users, only: [:show, :index] do
    get 'friends', to: 'friendships#index'
    post 'friend', to: 'friendships#create'
    post 'accept', to: 'friendships#update'
    delete 'unfriend', to: 'friendships#destroy'
  end
  
  resources :posts 
  resources :comments
  resources :likes, only: [:index, :create, :destroy]
  resources :notifications, only: [:index]
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy

  default_scope { order(created_at: :desc) }

  after_create :create_notification

  def create_notification
    notifications.create(user: post.user) unless user == post.user
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: %i[edit update destroy]
  before_action :comment_owner?, only: %i[edit update destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    return unless @comment.save

    flash[:notice] = 'Comment was successfully posted.'
    redirect_back(fallback_location: root_path)
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      flash[:notice] = 'Comment was successfully updated.'
      redirect_to @comment.post
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = 'Comment was successfully deleted.'
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_owner?
    redirect_back(fallback_location: root_path) unless @comment.user == current_user
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class='comment p-2 d-flex <%= 'card' if edit_path?%>'>
  <div class='d-flex col-11 p-0'>
    <%= avatar_for(comment.user) %>
    <div class='ml-2 col p-0'>
      <%= name_for(comment.user)%>
      <small class="post_time ml-1"><%= time_ago_in_words(comment.created_at) %> ago </small>
      <% if edit_path?%>
        <%= form_for comment do |f| %>
          <%= render 'devise/shared/error_messages', resource: f.object %>
          <%= f.hidden_field :post_id, value: comment.post.id %>
          <%= f.text_field :content, placeholder: "Write a comment...", class: 'form-control', required: true, autocomplete: 'off' %>
          <%= f.submit "Comment", class: "btn btn-primary" %>
        <% end %>
      <% else %>
        <p class="m-0"> <%= comment.content%> </p>
        <% if liked?(comment) %>
          <%= link_to like_path(like_id(comment)), class: 'liked', method: :delete do%>
            UnLike
          <% end %>
        <% else %>
          <%= link_to likes_path(likeable_data(comment)), class: '', method: :post do%>
            Like
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <% if comment.user == current_user && !edit_path? %>
    <div class="dropdown ">
      <button class="btn " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= fa_icon "ellipsis-h" %>
      </button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to "Edit", edit_comment_path(comment), class: 'btn ' %>
        <%= button_to "Delete", comment, :method => :delete, class: 'btn ' %>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_comment_form.html.erb
<%= form_for current_user.comments.new do |f| %>
  <%= render 'devise/shared/error_messages', resource: f.object %>
  <%= f.hidden_field :post_id, value: post.id %>
  <%= f.text_field :content, placeholder: "Write a comment...", class: 'form-control', required: true, autocomplete: 'off' %>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>

app/views/comments/edit.html.erb
<% provide(:title, 'Edit Comment') %>
<%= render partial: "comment", locals: {comment: @comment} %>