config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'friendships/index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root 'posts#index'
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :users, only: [:show, :index] do
    get 'friends', to: 'friendships#index'
    post 'friend', to: 'friendships#create'
    post 'accept', to: 'friendships#update'
    delete 'unfriend', to: 'friendships#destroy'
  end
  
  resources :posts 
  resources :comments
  resources :likes, only: [:index, :create, :destroy]
  resources :notifications, only: [:index]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,:confirmable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :friendships, dependent: :destroy

  has_many :friends,
           -> { where friendships: { status: 2 } },
           through: :friendships

  has_many :pending_friends,
           -> { where friendships: { status: 0 } },
           through: :friendships,
           source: :friend

  has_many :requested_friends,
           -> { where friendships: { status: 1 } },
           through: :friendships,
           source: :friend

  # user data

  def full_name
    "#{first_name} #{last_name}"
  end

  # OmniAuth

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      full_name = auth.info.name.split
      user.first_name = full_name.first
      user.last_name = full_name.last
      user.profile_image = auth.info.image
    end
  end

  # Friendships methods

  def strangers
    User.all - [self] - friends - pending_friends - requested_friends
  end

  def friend_request(friend)
    friendships.create(friend: friend, status: 0)
    friend.friendships.create(friend: self, status: 1)
  end

  def accept_request(friend)
    relations(friend).each { |friendship| friendship.update(status: 2) }
  end

  def relations(friend)
    Friendship.where(user: self, friend: friend) + Friendship.where(user: friend, friend: self)
  end

  def friends_with?(friend)
    Friendship.where(user: self, friend: friend, status: 2).any?
  end

  def decline_request(friend)
    relations(friend).each(&:destroy)
  end

  alias remove_friend decline_request

  # Feed methods

  def feed
    Post.where(user: (friends + [self]))
  end

  # Notifications methods

  def unseen_notifs
    notifications - (@seen_notifs || seen_notifs)
  end

  def seen_notifs
    @seen_notifs ||= []
    @seen_notifs += unseen_notifs.select(&:seen)
  end

  def see_all_notifs
    unseen_notifs.each { |notification| notification.update(seen: true) }
  end

  # callbacks

  def on_friendship_created(friendship)
    notifications.create(notifiable: friendship) unless friendship.status == 'requested'
  end

  def on_friendship_accepted(friendship)
    notifications.create(notifiable: friendship)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if (user = User.find_by(email: @user.email))
      @user = user
    end

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts = User.find(params[:id]).posts
  end

  def index
    @users = current_user.strangers
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def avatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    profile_image = user.profile_image || gravatar_url
    image = image_tag(profile_image, alt: user.full_name)
    "<a href='#{user_path(user)}' class='avatar'>#{image}</a>".html_safe
  end

  def name_for(user)
    "<a href='#{user_path(user)}' class='username'> #{user.full_name} </a>".html_safe
  end
end

app/views/users/_user.html.erb
<div class="user card">
  <div class="avatar-name">
    <%= avatar_for user %>
    <div class="name-time">
      <%= name_for(user)%>
    </div>
  </div>
  <% if current_user.pending_friends.include?(user) %>
    <%= button_to 'Cancel friend request', user_unfriend_path(user, format: :cancel_request ), method: :delete, class: 'btn btn-danger'%>
  <% elsif current_user.requested_friends.include?(user) %>
    <div class="d-flex justify-content-end">
      <%= button_to 'Accept', user_accept_path(user), class: 'btn btn-primary mr-2'%>
      <%= button_to 'Reject', user_unfriend_path(user, format: :reject_request ), method: :delete, class: 'btn btn-danger'%>
    </div>
  <% elsif current_user.friends_with?(user) %>
    <%= button_to 'Unfriend', user_unfriend_path(user), method: :delete, class: 'btn btn-danger'%>
  <% else %>
    <%= button_to 'Send friend request', user_friend_path(user), class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<%= render @users %>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>
<div class= "card mb-2 px-3 py-3">
  <div class='col-2'>
    <%= avatar_for(@user)%>
  </div>
  <strong>Bio:</strong>
  <%= @user.bio%>
</div>
<%= render @posts %>