config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'friendships/index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root 'posts#index'
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :users, only: [:show, :index] do
    get 'friends', to: 'friendships#index'
    post 'friend', to: 'friendships#create'
    post 'accept', to: 'friendships#update'
    delete 'unfriend', to: 'friendships#destroy'
  end
  
  resources :posts 
  resources :comments
  resources :likes, only: [:index, :create, :destroy]
  resources :notifications, only: [:index]
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  default_scope { order(created_at: :desc) }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]
  before_action :post_owner?, only: %i[edit update destroy]

  def index
    @post = Post.new
    @posts = current_user.feed
    @comment = current_user.comments.build
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = 'Post was successfully created.'
      redirect_back(fallback_location: root_path)
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post was successfully updated.'
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Post was successfully deleted.'
    redirect_to root_url
  end

  private

  def post_owner?
    redirect_to root_url unless @post.user == current_user
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def show_path?
    request.fullpath.match(%r{posts/\d+})
  end
end

app/views/posts/_post.html.erb
<% unless post.nil? %>
  <div class='post card'>
    <div class="header">
      <div class="avatar-name">
        <%= avatar_for post.user %>
        <div class="name-time">
          <%= name_for(post.user)%>
          <%= link_to(post) do%>
            <p class="post_time"> Published <%= time_ago_in_words(post.created_at) %> ago </p>
          <% end %>
        </div>
      </div>
      <% if post.user == current_user && !edit_path? %>
        <div class="dropdown">
          <button class="btn " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= fa_icon "ellipsis-h" %>
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <%= link_to "Edit", edit_post_path(post), class: 'btn ' %>
            <%= button_to "Delete", post, :method => :delete, class: 'btn ' %>
          </div>
        </div>
      <% end %>
    </div>
    <% if  edit_path? %>
      <%= render 'post_form'%>
    <% end %>
    <% unless edit_path? %>
      <div class='content'>
        <%= post.content %>
      </div>
      <div class='stats d-flex justify-content-end text-secondary'>
        <%= link_to likes_path(likeable_data(post)), class: 'likes-count' do %>
          <%= pluralize(post.likes.count, 'Like')%>
        <% end %>
        <%= link_to post_path(post), class: 'likes-count ml-2' do %>
          <%= pluralize(post.comments.count, 'Comment')%>
        <% end %>
      </div>
      <div class="dropdown-divider m-0"></div>
      <div class='like-comment row '>
        <% if liked?(post) %>
          <%= link_to like_path(like_id(post)), class: 'btn col liked', method: :delete do%>
            <%= fa_icon "thumbs-up", class: "mr-2" %> UnLike
          <% end %>
        <% else %>
          <%= link_to likes_path(likeable_data(post)), class: 'btn col', method: :post do%>
            <%= fa_icon "thumbs-up", class: "mr-2" %> Like
          <% end %>
        <% end %>
        <a class="btn col " data-toggle="collapse" href="#Comments-area<%= post.id%>" role="button" aria-expanded="false" aria-controls="collapseExample">
          <%= fa_icon "comment", class: "mr-2" %> Comment
        </a>
      </div>
      <div class="comment-area collapse <%= 'show' if show_path? %>" id="Comments-area<%= post.id%>">
        <div class="dropdown-divider mt-0"></div>
        <%= render partial: "comments/comment_form", locals: {post: post} %>
        <small class="text-muted"><%= render post.comments %></small>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_post_form.html.erb
<%= form_for @post do |f|%>
  <%= render 'devise/shared/error_messages', resource: f.object %>
  <div class="field">
    <%= f.text_field :content, placeholder: "What's on your mind?" , class: 'form-control', required: true, autocomplete: 'off'%>
  </div>
  <%= f.submit "Post", class: "btn btn-primary d-none" %>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, 'Edit Post') %>
<%= render @post %>

app/views/posts/index.html.erb
<% provide(:title, 'Home') %>
<div class= "new-post card mb-5">
  <%= avatar_for current_user %>
  <%= render 'post_form'%>
</div>
<%= render @posts %>

app/views/posts/new.html.erb
<% provide(:title, 'Create Post') %>
<%= render 'post_form'%>

app/views/posts/show.html.erb
<% provide(:title, 'Post') %>
<%= render @post %>