config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'friendships/index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root 'posts#index'
  end

  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :users, only: [:show, :index] do
    get 'friends', to: 'friendships#index'
    post 'friend', to: 'friendships#create'
    post 'accept', to: 'friendships#update'
    delete 'unfriend', to: 'friendships#destroy'
  end
  
  resources :posts 
  resources :comments
  resources :likes, only: [:index, :create, :destroy]
  resources :notifications, only: [:index]
end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |message_type, message| %>
    <div class="alert-container">
      <div class="alert alert-<%= alert_type(message_type) %> fade show" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <header >
    <div class='wrapper'>
      <div class="container top d-flex justify-content-between">
        <div class="avatar-name">
          <%= avatar_for current_user %>
          <h1 class=" ml-2"> <%= yield(:title) %> </h1>
        </div>
        <div class="d-flex">
          <%= name_for(current_user)%>
        </div>
      </div>
      <div class="container bottom">
        <nav>
          <%= link_to root_url, :class => 'navbar-link' do%>
            <%= fa_icon "home" %>
          <% end %>
          <%= link_to users_path, :class => 'navbar-link' do%>
            <%= fa_icon "search" %>
          <% end %>
          <%= link_to user_friends_path(current_user, format: :requests_received), :class => 'navbar-link' do%>
            <%= fa_icon "users" %>
          <% end %>
          <%= link_to notifications_path, :class => 'navbar-link notifications' do%>
            <%= fa_icon "bell" %>
            <% unless (notifs = current_user.unseen_notifs.count).zero? %>
              <div> <span><%=notifs%></span> </div>
            <% end %>
          <% end %>
          <%= link_to user_path(current_user), :class => 'navbar-link' do%>
            <%= fa_icon "user" %>
          <% end %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        </nav>
      </div>
    </div>
  </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <main>
      <div class="timeline_container px-sm-5">
        <%= yield %>
      </div>
    </main>
  </body>
</html>